[workspace]
members = ["crypt", "excel_dll_postgres_rust"]
resolver = "2"


[profile.release]
opt-level = "z" # opt-level = "s" или "z" для максимального уменьшения размера
lto = true
debug = false
panic = 'abort'